// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC8lnkX3MvJVNtxZzXKB4ZtxHFRBU1MYA',
    appId: '1:144305290224:web:b8870dc5bdd0df09687b35',
    messagingSenderId: '144305290224',
    projectId: 'fleetsync-7b223',
    authDomain: 'fleetsync-7b223.firebaseapp.com',
    storageBucket: 'fleetsync-7b223.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2qi0gbMlr-ik-XDLvLlmxSyPBX_6TKQs',
    appId: '1:144305290224:android:27fab9d03a46756f687b35',
    messagingSenderId: '144305290224',
    projectId: 'fleetsync-7b223',
    storageBucket: 'fleetsync-7b223.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAgxRZQLA_swIVRUXcpufQtdqbsS5yU9g',
    appId: '1:144305290224:ios:90f22e005391b8ad687b35',
    messagingSenderId: '144305290224',
    projectId: 'fleetsync-7b223',
    storageBucket: 'fleetsync-7b223.firebasestorage.app',
    iosBundleId: 'com.archyuniq.fleetsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAgxRZQLA_swIVRUXcpufQtdqbsS5yU9g',
    appId: '1:144305290224:ios:90f22e005391b8ad687b35',
    messagingSenderId: '144305290224',
    projectId: 'fleetsync-7b223',
    storageBucket: 'fleetsync-7b223.firebasestorage.app',
    iosBundleId: 'com.archyuniq.fleetsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC8lnkX3MvJVNtxZzXKB4ZtxHFRBU1MYA',
    appId: '1:144305290224:web:1eb67fbc6fc3b0b7687b35',
    messagingSenderId: '144305290224',
    projectId: 'fleetsync-7b223',
    authDomain: 'fleetsync-7b223.firebaseapp.com',
    storageBucket: 'fleetsync-7b223.firebasestorage.app',
  );
}
